### ISSUE TITLE
Antidote 10 support

### ISSUE THREAD

**Issue by AdrianSimionov** [Heziode/obsidian-antidote#3]
I tested the plugin with both Antidote version 10 and version 11 and it currently works only with version 11.

Please note, the integration of "other" applications works with Antidote 10.

Either:
1) Change README.md and clarify that this plugin works only with Antidote 11.
2) Fix the plugin so that it works with Antidote version 10, too.

**Comment by Heziode** [comment]
I am currently working on it.

There is a working version on [refactor](/Heziode/obsidian-antidote/tree/refactor) branch, which is a refactor based on a revers-engineered version of the VS Code official Antidote plugin (since the client lib provided by Antidote seems outdated and in which some functionalities seems missing).

The state of this branch is dirty. The code work, but I need to clean it, and add support of some features, like fix a word in multiple place of a document.
